#!/bin/sh


./src/dseq 2014-05-01 1 2014-05-02 >> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
2014-05-01
2014-05-02
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "./src/dseq 2014-05-01 1 2014-05-02 failed"
    exit 1
fi


./src/dseq 2014-05-01 5 2014-05-30 >> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
2014-05-01
2014-05-06
2014-05-11
2014-05-16
2014-05-21
2014-05-26
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "2014-05-01 5 2014-05-30 failed"
    exit 1
fi
    

./src/dseq 2014-05-30 -5 2014-05-03 >> tests/threearg-out.$$
if diff -c tests/twoarg-out.$$ - <<EOF
2014-05-30
2014-05-25
2014-05-20
2014-05-15
2014-05-10
2014-05-05
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "./src/dseq 2014-05-30 -5 2014-05-03 failed"
    exit 1
fi

## FAIL - extra newline
if [ $(./src/dseq 2014-05-30 5 2014-05-03 | wc -l) != "0" ];
then
    echo "./src/dseq 2014-05-30 5 2014-05-03 failed"
    exit 1
fi


if [ $(./src/dseq 2014-05-01 -1 2014-05-02 | wc -l) != "0" ];
then
    echo "./src/dseq 2014-05-01 -1 2014-05-02 failed"
    exit 1
fi


## FAIL - doesn't check arg 2 for proper integerhood
./src/dseq 2014-05-01 2014-04-02 2014-05-02 2> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
./src/dseq: invalid step argument: 2014-04-02
Try 'dseq --help' for more information.
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    exit 1
fi

./src/dseq 2014-05-01 aaa 2014-05-02 2> tests/threearg-out.$$

if diff -c tests/threearg-out.$$ - <<EOF
./src/dseq: invalid step argument: 2014-04-02
Try 'dseq --help' for more information.
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    exit 1
fi
