#!/bin/sh


./src/dseq 2014-05-01 1 2014-05-02 >> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
2014-05-01
2014-05-02
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "./src/dseq 2014-05-01 1 2014-05-02 failed"
    exit 1
fi


./src/dseq 2014-05-01 5 2014-05-30 >> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
2014-05-01
2014-05-06
2014-05-11
2014-05-16
2014-05-21
2014-05-26
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "2014-05-01 5 2014-05-30 failed"
    exit 1
fi
    

./src/dseq 2014-05-30 -5 2014-05-03 >> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
2014-05-30
2014-05-25
2014-05-20
2014-05-15
2014-05-10
2014-05-05
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "./src/dseq 2014-05-30 -5 2014-05-03 failed"
    exit 1
fi

./src/dseq 2014-05-30 5 2014-05-03 >> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
2014-05-30
2014-05-25
2014-05-20
2014-05-15
2014-05-10
2014-05-05
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "./src/dseq 2014-05-30 5 2014-05-03 failed"
    exit 1
fi


if [ $(./src/dseq 2014-05-01 -1 2014-05-02 | wc -l) != "2" ];
then
    echo "./src/dseq 2014-05-01 -1 2014-05-02 failed"
    exit 1
fi


./src/dseq 2014-05-01 2014-04-02 2014-05-02 2> tests/threearg-out.$$
if diff -c tests/threearg-out.$$ - <<EOF
./src/dseq: invalid step argument: 2014-04-02
Try 'dseq --help' for more information.
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "failed to detect 2014-05-02 as invalid step argument"
    exit 1
fi

./src/dseq 2014-05-01 aaa 2014-05-02 2> tests/threearg-out.$$

if diff -c tests/threearg-out.$$ - <<EOF
./src/dseq: invalid step argument: 2014-04-02
Try 'dseq --help' for more information.
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "failed to detect aaa as invalid step argument"
    exit 1
fi


./src/dseq aaa 5 2014-05-02 2> tests/threearg-out.$$

if diff -c tests/threearg-out.$$ - <<EOF
./src/dseq: bad date format: aaa
Try 'dseq --help' for more information.
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "failed to detect aaa as invalid start date argument"
    exit 1
fi


./src/dseq 2014-05-01 5 asdfjkl 2> tests/threearg-out.$$

if diff -c tests/threearg-out.$$ - <<EOF
./src/dseq: bad date format: asdfjkl
Try 'dseq --help' for more information.
EOF
then
    rm -f tests/threearg-out.$$
else
    rm -f tests/threearg-out.$$
    echo "failed to detect asdfjkl as invalid step argument"
    exit 1
fi
